name: Deploy and Notify
on:
  workflow_dispatch:
  push:
    branches: [ main,"release/*" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # レポジトリのチェックアウト
      - name: Check out the repo
        uses: actions/checkout@v4
      # dockerxを使用可能にする
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      # github packagesにログイン
      - name: Login GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # ユーザー名に大文字が含まれる場合に備えて小文字に変換する
      - name: Convert to lowercase
        id: lowercase
        run: echo "::set-output name=actor::$(echo "${{ github.actor }}" | tr '[:upper:]' '[:lower:]')"
      # プロジェクトルートのDockerfileをビルドして、ghcr.io/username/guild-mng-bot:latestとして公開する
      - name: build for bot
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ steps.lowercase.outputs.actor }}/guild-mng-bot:latest

  notify-discord:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set DISCORD_WEBHOOK_URL environment variable
        run: echo "DISCORD_WEBHOOK_URL=${{ secrets.DISCORD_WEBHOOK_URL }}" >> $GITHUB_ENV
      # Discordに通知する
      - name: Notify Discord
        # secrets.DISCORD_WEBHOOK_URLがある場合のみ実行
        if: env.DISCORD_WEBHOOK_URL != ''
        run: |
          # Embedメッセージの内容を作成
          if [ "${{ needs.deploy.result }}" = "success" ]; then
            EMBED_TITLE="✅デプロイに成功しました"
            EMBED_COLOR=5763719
          else
            EMBED_TITLE="🚫デプロイに失敗しました"
            EMBED_COLOR=15548997
          fi
          PORTAINER_URL="https://portainer.worldcell.yagloud.com/#!/home"
          REPO_URL="https://github.com/${{ github.repository }}"
          DEPLOY_WORKFLOW_URL=$REPO_URL/actions/runs/${{ github.run_id }}
          PAYLOAD='{
            "embeds": [
              {
                "title": "'${EMBED_TITLE}'",
                "description": "[デプロイ先]('${PORTAINER_URL}')\n[リポジトリ]('${REPO_URL}')\n[ワークフロー]('${DEPLOY_WORKFLOW_URL}')",
                "color": '${EMBED_COLOR}'
              }
            ]
          }'
          # DiscordにWebhookを送信
          curl -X POST -H "Content-Type: application/json" -d "$PAYLOAD" "${{ secrets.DISCORD_WEBHOOK_URL }}"